on: push
name: deploy
jobs:
  Deploy-Action:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 2

      - name: Use Node.js 20.x
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '20.x'

      - name: Install pnpm
        run: npm i pnpm -g

      - name: Install Dependencies
        run: pnpm i

      - name: Build Packages
        run: pnpm run build
        
      - name: Deploy gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./.vitepress/dist
